// Generated by ts-to-zod
import { z } from "zod";

export const urlSourceSchema = z.object({
    url: z.object({
        fetchedAt: z.string()
    })
});

export const debugToolsSourceSchema = z.object({
    debugTools: z.object({
        modifiedAt: z.string()
    })
});

export const remoteResourceSchema = z.object({
    id: z.string(),
    url: z.string(),
    name: z.string(),
    current: z.object({
        source: z.union([urlSourceSchema, debugToolsSourceSchema]),
        contents: z.string(),
        contentType: z.string()
    })
});

export const getFeaturesResponseSchema = z.object({
    features: z.object({
        remoteResources: z.object({
            resources: z.array(remoteResourceSchema)
        })
    })
});

export const apiSchema = z.object({
    getFeatures: getFeaturesResponseSchema.optional()
});

